### ISSUE TITLE
Bug: Incorrect Optional Dependencies

### ISSUE THREAD

**Issue by jcayers20** [jcayers20/mkdocs-autoapi#61]
Just noticed that in my `pyproject.toml`, I have the following optional dependencies:

```toml
[project.optional-dependencies]
python-legacy = ["mkdocstrings[python]>=0.19.0"]
python = ["mkdocstrings[python-legacy]>=0.19.0"]
```

The extra names and package requirements are not aligned, which requires a fix.
